from scrapy import Item, Field


class DetailedItem(Item):
    id = Field()
    categoryId = Field()
    locationId = Field()
    metroId = Field()
    metroType = Field()
    sharing = Field()
    coords = Field()
    address = Field()
    title = Field()
    userType = Field()
    time = Field()
    description = Field()
    parameters = Field()
    images = Field()
    price = Field()
    seller = Field()
    shopId = Field()
    shopType = Field()
    stats = Field()
    contacts = Field()
    needToCheckCreditInfo = Field()
    firebaseParams = Field()
    adjustParams = Field()
    deliveryC2C = Field()
    video = Field()
    titleGenerated = Field()
    autodeal = Field()
    directionId = Field()
    autoteka = Field()
    anonymousNumber = Field()
    shortTermRent = Field()
    needToCheckModelSpecs = Field()
